### ISSUE TITLE
Configuration of delimiters

### ISSUE THREAD

**Issue by hagenw** [hagenw/sphinxcontrib-katex#6]
This is a follow up on #3 as the current solution is not perfect as indicated in #5.

The current situation is as follows:
We introduce the special config variables `katex_inline` and `katex_display`. Those are then added to the `delimiters` entry inside the string variable `katex_options`.

Possible improvements:

**1.)** Add the entries of `katex_inline` and `katex_display` only to `delimiters` if the string `'delimiters'` cannot be found inside `katex_options`.
**Con:** If the custom user setting of `delimiters` doesn't contain the delimiters specified in `katex_inline` and `katex_display` the math will not be rendered at all. This could happen, if a user decides after some time to change for example the `katex_inline` setting, but forgets to adjust the custom `delimiters` setting.
**Pro:** We don't have to add something to the `katex_options` string.

**2.)** Allow for `katex_inline`, `katex_display` and `delimiters` settings and simply merge them together.
**Con:** As the `delimiters` setting is inside the string variable `katex_options` it might be complicated to find the right positions for adding the contents of `katex_inline` and `katex_display`. In addition, we have to check what happens with duplicated entries.
**Pro:** This should be bullet proof from a user perspective as you cannot break it, but also gives you maximum flexibility in configuring it.

**3.)** Abandon `katex_inline` and `katex_display` and only use the `delimiters` entry in `katex_options`. The default inline and default display delimiters will be automatically extracted from there.
**Con:** It will be not obvious to a user which of the `display: true` entries in `delimiters` will be used as the display delimiter in KaTeX. It might be complicated to extract the delimiters from the string variable `katex_options`.
**Pro:** Only one setting for the used delimiters, which is in addition compatible with the way it is described in the KaTeX documentation. If the user is used to KaTeX it should be easy to use this plugin.

**4.)** Abandon `katex_inline` and `katex_display` and add the new config variable `delimiters`. The same as in 3.) applies, but now we don't have to extract the variable from the `katex_options` string.
**Con:** Beside the same issue that it might be not obvious to a user which delimiter is used internally, it is inconsistent with the KaTeX documentation as we allow for all settings inside `katex_options`, but the `delimiters` one. 
**Pro:** We don't have to add something to the `katex_options` string and have again only one setting for the delimiters as in 3.).

@bryanwweber: any thoughts on which might be the best solution, or if there are more pro and cons?

**Comment by bryanwweber** [comment]
A few thoughts: In my opinion, 3) and 4) are not good options. The cons there are too strong, in my opinion.

2) is possible if we can parse the `katex_options` string with the (built-in) JSON module. Then, the `delimiters` will be a key in a dictionary whose value is a list of strings. However, munging the `katex_options` so it can be read by the JSON module isn't necessarily straightforward. In particular, the JSON standard is much stricter than the object used by KaTeX autorender; the difference most likely to cause trouble is that everything that is a key (`"delimiters"`, `"left"`, `"right"`, etc.) has to be enclosed in double (not single) quotes. This is not required by the object that is used in the .js script, and it is not demonstrated on the KaTeX autorender README, plus the resulting error message isn't that helpful, so users are not likely to get what the problem is. In the end, I don't think this is a good solution - it is too complicated, and too prone to breaking/bugs.

I think 1) is the best option. To the pros, I would add that it is the simplest option, both for the user to understand and for us to implement, which means there is the least chance of a bug. I also think that the user would figure out what happened if their math suddenly stopped rendering (presumably there is a commit message where it changed at some point in the past).

**Comment by hagenw** [comment]
1) was implemented by #7
